stages:
  - build
  - test

build-application:
  image: node:16
  stage: build
  script:
    - echo "Building application"
    - cd client/
    - npm install
    - npm run build

test-application:
  image: node:16
  stage: test
  script:
    - echo "test application"
    - npm run test

